#!/usr/bin/env bash
BIN_PATH_INSTALLED="/usr/local/bin/crowdsec-cloudflare-bouncer"
BIN_PATH="./crowdsec-cloudflare-bouncer"
CONFIG_DIR="/etc/crowdsec/bouncers/"
PID_DIR="/var/run/crowdsec/"
SYSTEMD_PATH_FILE="/etc/systemd/system/crowdsec-cloudflare-bouncer.service"
CACHE_DIR="/var/lib/crowdsec/cache/"

LAPI_KEY=""

gen_apikey() {
    which cscli > /dev/null
    if [[ $? == 0 ]]; then 
        echo "cscli found, generating bouncer api key."
        SUFFIX=`tr -dc A-Za-z0-9 </dev/urandom | head -c 8`
        LAPI_KEY=`cscli bouncers add crowdsec-cloudflare-bouncer-${SUFFIX} -o raw`
        READY="yes"
    else 
        echo "cscli not found, you will need to generate api key."
        READY="no"
    fi
}

gen_config_file() {
    LAPI_KEY=${LAPI_KEY} envsubst < ./config/crowdsec-cloudflare-bouncer.yaml > "${CONFIG_DIR}crowdsec-cloudflare-bouncer.yaml"
}


install_cloudflare_bouncer() {
	install -v -m 755 -D "${BIN_PATH}" "${BIN_PATH_INSTALLED}"
	mkdir -p "${CONFIG_DIR}"
	mkdir -p "${CACHE_DIR}"
	cp "./config/crowdsec-cloudflare-bouncer.yaml" "${CONFIG_DIR}crowdsec-cloudflare-bouncer.yaml"
	CFG=${CONFIG_DIR} PID=${PID_DIR} BIN=${BIN_PATH_INSTALLED} envsubst < ./config/crowdsec-cloudflare-bouncer.service > "${SYSTEMD_PATH_FILE}"
	systemctl daemon-reload
}

start_service(){
    if [ "$READY" = "yes" ]; then
        systemctl start crowdsec-cloudflare-bouncer.service
    else
        echo "service not started. You need to get an API key and configure it in ${CONFIG_DIR}crowdsec-cloudflare-bouncer.yaml"
    fi
    echo "The crowdsec-cloudflare-bouncer service has been installed!"
}

install_bouncer(){
    echo "Installing crowdsec-cloudflare-bouncer"
    install_cloudflare_bouncer
    gen_apikey

    gen_config_file
    systemctl enable crowdsec-cloudflare-bouncer.service
}


if ! [ $(id -u) = 0 ]; then
    echo "Please run the install script as root or with sudo"
    exit 1
fi

install_bouncer
echo "Please configure '${CONFIG_DIR}crowdsec-cloudflare-bouncer.yaml'."
echo "Configuration can be autogenerated using /usr/local/bin/crowdsec-cloudflare-bouncer -g <CF_TOKEN_1>,<CF_TOKEN_2> "
echo "After configuration run the command 'systemctl start crowdsec-cloudflare-bouncer.service' to start the bouncer"
