name: Update Docker Hub README

on:
  push:
    branches:
      - main
    paths:
      - 'docker/README.md'

permissions:
  contents: read

jobs:
  update-docker-hub-readme:
    name: Update the README on Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v4
      -
        name: Update docker hub README
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: crowdsecurity/cloudflare-bouncer
          readme: "./docker/README.md"
